### PR TITLE
Support outputting Clang compilation database

### PR DESCRIPTION
**Pull request by raphael-theriault-swi**
See https://clang.llvm.org/docs/JSONCompilationDatabase.html for details about the format. Used by tools such as [`clangd`](https://clangd.llvm.org/installation#project-setup) to provide much better intellisense.

Also updates a bunch of dependencies.

### CODE REVIEW

**Review by cheempz — APPROVED** [review]
LGTM but curious because I'm still very lost--how is the compilation database generated ;)  From quick read of the linked page it seems it's with a clang compiler flag?

**Comment by raphael-theriault-swi** [comment]
It's generated by the script, from the flags pushed to `dbFlags`

**Comment by cheempz** [comment]
> It's generated by the script, from the flags pushed to `dbFlags`

Ah gotcha, so up to the user of this library, makes sense :)

**Review by cheempz — APPROVED** [review]
Thanks for the helpful comments @raphael-theriault-swi!

**Pull request merged**
